services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DB_NAMESPACE: auth
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 50
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./dev/init-postgres.sh:/docker-entrypoint-initdb.d/init.sh

  maildev:
    image: maildev/maildev
    ports:
      # - 1025:1025
      - 1447:1080

  gotrue:
    image: supabase/gotrue:v2.169.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LOG_LEVEL: "debug"

      GOTRUE_API_HOST: "0.0.0.0"
      PORT: "1227"
      API_EXTERNAL_URL: "http://localhost:1227"
      GOTRUE_SITE_URL: "http://localhost:1227"
      GOTRUE_URI_ALLOW_LIST: "http://localhost:1227,http://localhost:5173"

      GOTRUE_DB_DRIVER: "postgres"
      DATABASE_URL: "postgres://supabase_auth_admin:root@postgres:5432/postgres?sslmode=disable"
      DB_NAMESPACE: "auth"

      GOTRUE_JWT_SECRET: "not-so-secret-dev-secret"
      GOTRUE_COOKIE_SECRET: "not-so-secret-dev-cookies"
      GOTRUE_JWT_EXP: "315360000"

      GOTRUE_SMTP_HOST: "maildev"
      GOTRUE_SMTP_PORT: "1025"
      GOTRUE_SMTP_ADMIN_EMAIL: "wind@jim.computer"

      GOTRUE_EXTERNAL_GOOGLE_ENABLED: "true"
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: "${GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID}"
      GOTRUE_EXTERNAL_GOOGLE_SECRET: "${GOTRUE_EXTERNAL_GOOGLE_SECRET}"
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: "http://localhost:1227/callback"
    ports:
      - "1227:1227"

volumes:
  pg_data:
